---
functional:
  - 1. website must have main page
  - 1.1 main page must contain a Header
  - 1.1.1 Header must contain logo, brand name, user's menu
  - 1.1.2 Header must contain brand name
  - 1.1.3 Header must contain user's menu
  - 1.2 main page must contain "Create a game" button
  - 1.3 main page must contain game side bar
  - 1.3.1 side bar must contain "lobby"
  - 1.3.1 side bar must contain "Tournaments"
  - 1.3.1 side bar must contain "Completed Games"
  - 1.3.1 user must be able to switch between "lobby", "Tournaments", "Completed Games"
  - 1.4 main page must contain Chat side bar
  - 1.4.1 it must be possible to switch between "General" and "Notification" in the Chat
  - 1.5 main page must contain "LEADERBOARD"
  - 1.6 main page must contain a footer.
  - 2. website must have separate page for unsigned users
  - 2.1 website must have "sing in" buttom on the unsigned users page
  - 2.2 website must have "sign up" buttom on the unsigned users page
  - 2.3 website must have "try a simple battle" buttom on the unsigned users page
  - 3. website must have Sign up page
  - 3.1 user must be able to sign up with Github
  - 3.2 user must be able to sign up with Discord
  - 3.3 user must be able to sign up via email
  - 3.4 it must be imposibble to register more than one profile with the same name
  - 3.5 it must be imposibble to register more than one profile with the same email
  - 3.6 email must be like "%@%.%"
  - 3.7 name must be longer than 3 charters
  - 3.8 password must be longer than 6 charters , less than 16 characters and must have one special character
  - 4. website must have Sign in page
  - 4.1 user must be able to sign in with Github
  - 4.2 user must be able to sign in with Discord
  - 4.3 user must be able to sign in via email
  - 4.4 during Sign In attempt with incorrect password web page must show "INVALID_PASSWORD" error into log in side bar
  - 4.5 during Sign In attempt with incorrect email web page must show "EMAIL_NOT_FOUND" error into log in side bar
  - 5. user must be able to change user name
  - 6. user must be able to connect Github after registration
  - 7. user must be able to connect Discord after registration
  - 8. user must be able to switch his "weapon"(programming language)
  - 9. user must be able to Sign out
  - 10. user must be able to delete profile
  - 11. user must be able to join avalible game
  - 12. user must be able to create new game
  - 12.1 create new game menu must give users opportunity to choose level, game type, time control, kind of task
  - 12.1 during the creating new game user can choose level
  - 12.1.1 level range 1-4
  - 12.2 during the creating new game user can choose game type
  - 12.2.1 user must be able to play with others users
  - 12.2.2 user must be able to play with a friend
  - 12.2.3 user must be able to play with a bot
  - 12.3 during the creating new game user can choose time control
  - 12.3.1 time control range 3-60 minutes
  - 12.4 during the creating new game user can choose kind of task
  - 13. website must have a game page
  - 13.1 game page must have "Task" window
  - 13.2 game page must have "Output" window
  - 13.3 game page must have "Chat" window
  - 13.3.1 "Chat" window must have "General"
  - 13.3.2 "Chat" window must have "Notifications"
  - 13.3.3 It must be possible to swith beetween "General" and "Notifications"
  - 13.3.4  user must be able to sent messages in the chat
  - 13.4 game page must have game timer
  - 13.5 game page must have user's code editor
  - 13.5.1 user must be able to choose between dark and light color mode
  - 13.5.2 user must be able to use "Vim" to write a code
  - 13.5.3 user must be able to run user's code
  - 13.5.4 user must be able to reset user's editor
  - 13.5.5 user must be able to give up
  - 13.5.6 every text row in the editor must have a sequence number
  - 13.5.7 user must be able to switch programing lenguage
  - 13.5.7.1 Clojure 1.11.2.1 must be as avalible lenguage
  - 13.5.7.2 C++ 20 must be as avalible lenguage
  - 13.5.7.3 C# 6.0.100 must be as avalible lenguage
  - 13.5.7.4 Dart 2.17.6 must be as avalible lenguage
  - 13.5.7.5 Golang 1.19.0 must be as avalible lenguage
  - 13.5.7.6 Java 20 must be as avalible lenguage
  - 13.5.7.7 Node.JS 16.17.0 must be as avalible lenguage
  - 13.5.7.8 Kotlin 1.9.10 must be as avalible lenguage
  - 13.5.7.9 Php 8.1.8 must be as avalible lenguage
  - 13.5.7.10 Rupy 3.2.2 must be as avalible lenguage
  - 13.5.7.11 Typescript 4.7.4 must be as avalible lenguage
  - 13.6 game page must show second player's code redactor
  - 13.6.1 both players must be able to see code of each other
  - 13.8 user must be able to retern to the home page from game page
  - 13.9 game page must have game music accompaniment
  - 13.10 game page must have online user counter
  - 13.11 if users's solution is incorrect; issues must be showed in output without game stop
  - 13.12 if user won; winner banner must be showed
  - 13.13 if an opponent won; loser banner must be showed
  - 13.14 game must be stopped when someone win or give up or time is gone
  - 13.15 user must be able to switch to another page without losing the game
  - 13.16 user must be able to come back to the exisited game from another page
  - 13.17 user must be able to rematch a game with the same opponent and with the same conditions(level, time, etc)
  - 13.18 user must be able to cancel a game "Game type" = "with other users" before an opponent founded.
  - 13.19 user must be able to send feedback
non-functional:
  - website must be
  - website must be capable of displaying content in multiple languages
  - website must be compatible with the all main web browsers(Google Chrome, Safari, Microsoft Edge, Mozilla Firefox, Opera), all versions not elder 36 months.
  - website must be able to handle heavy traffic (up to 1.000 users at ones)
  - website must be convenient on moble devises
  - website must be secure and protect user's data
  - website must be designed with ease of use in mind and
  optimized for speed
  -
implict:
  -
